package housy.nb;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

public class MainFrame extends javax.swing.JFrame implements Updatable {

    private Controller controller;
    private Model model;
    
    public MainFrame(Controller controller, Model model) {
        initComponents();
        initImageIcon();
        this.controller = controller;
        this.model = model;
        
        jMenuItem1.addActionListener(controller);
        jMenuItem2.addActionListener(controller);
        
        addWindowListener(controller);
        jTextArea1.setFont(model.font);
        jTextArea1.addKeyListener(controller);
        update();
    }
    
    private void initImageIcon() {
        try {
            Image icon = ImageIO.read(this.getClass().getResource("/res/notes.png"));
            this.setIconImage(icon);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }
    
    public String getDisplayText() {
        return jTextArea1.getText();
    }
    
    public void display(String text) {
        jTextArea1.setText(text);
        update();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jTextArea1.setName("mainTextField"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jMenu2.setText("S E T T I N G S");

        jMenuItem1.setText("Font Settings");
        jMenuItem1.setActionCommand("showFontSettings");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Color Settings");
        jMenuItem2.setActionCommand("showColorSettings");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        jTextArea1.setFont(model.font);
        jTextArea1.setBackground(model.bgColor);
        jTextArea1.setForeground(model.fgColor);
        jTextArea1.setCaretColor(model.fgColor);
        jTextArea1.setCaretPosition(jTextArea1.getText().length());
    }
}
